#!/bin/sh

# ci_post_clone.sh
# Generates Config.xcconfig from Xcode Cloud environment variables.
# Runs automatically after Xcode Cloud clones the repository.

set -e

CONFIG_FILE="$CI_PRIMARY_REPOSITORY_PATH/Config.xcconfig"

echo "Generating Config.xcconfig from environment variables..."

cat > "$CONFIG_FILE" <<EOF
// Auto-generated by ci_post_clone.sh — do not commit

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}

TFNSW_API_KEY=${TFNSW_API_KEY}
CAR_PARK_BASE_URL=${CAR_PARK_BASE_URL}

DEVELOPMENT_TEAM=${DEVELOPMENT_TEAM}
ENVIRONMENT=production
EOF

echo "Config.xcconfig generated at $CONFIG_FILE"
